version: '3.1'

services:

    elasticsearch:
       image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
       hostname: elasticsearch
       container_name: elasticsearch
       ports:
          - 9200:9200
          - 9300:9300
       environment:
          - discovery.type=single-node
       restart: always

    kibana:
       image: docker.elastic.co/kibana/kibana:7.7.0
       hostname: kibana
       container_name: kibana
       ports:
          - 5601:5601
       links:
          - elasticsearch:elasticsearch
       restart: always
