version: '3.1'

services:

    spiderfoot:
        build: .
        image: spiderfoot:3.0
        hostname: spiderfoot
        container_name: spiderfoot
        volumes:
            - $PWD/output:/var/lib/spiderfoot
        ports:
            - 5001:5001
        restart: always
