version: '3.1'

services:

    spiderfoot:
        build: .
        image: spiderfoot:3.0
        hostname: spiderfoot
        container_name: spiderfoot
        restart: always
        ports:
            - 5001:5001
